library(tidyverse)
library(rvest)
library(janitor) 
library(ggplot2)

url <-  "https://en.wikipedia.org/wiki/Opinion_polling_for_the_2022_French_presidential_election#Macron_vs._Le_Pen"
url_html <-read_html(url)
url_tables <-url_html%>%html_table(fill=TRUE) 
results<-url_tables[[9]]  
write_csv(results,paste0('data/',Sys.Date(),'_macron_lepen_polls','.csv'))   
